# Generated by Django 6.0 on 2025-12-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('reschedule_requested', 'Reschedule Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
    ]
