# Generated by Django 6.0 on 2026-01-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="onesignal_player_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
