# Generated by Django 6.0 on 2025-12-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_remove_appointment_confirmed_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='length_minutes',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
