# Generated by Django 6.0 on 2026-01-07 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0003_appointment_reschedule_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="Maximum number of attendees allowed for this service session.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="reschedule_token",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=100, unique=True
            ),
        ),
    ]
