# Generated by Django 6.0 on 2026-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0004_service_capacity_alter_appointment_reschedule_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="attendees",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
