# Generated by Django 6.0 on 2026-01-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0005_appointment_attendees"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("service", models.CharField(blank=True, max_length=255)),
                ("staff", models.CharField(blank=True, max_length=255)),
                ("time", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
