# Generated by Django 6.0 on 2026-01-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0007_alter_appointment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="deposit_amount",
        ),
        migrations.AddField(
            model_name="business",
            name="accepts_deposits",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="business",
            name="deposit_type",
            field=models.CharField(
                choices=[
                    ("flat", "Flat Amount"),
                    ("percentage", "Percentage of Service"),
                ],
                default="flat",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="deposit_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Enter the flat amount (e.g., 50.00) or percentage (e.g., 20 for 20%)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="reschedule_limit_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Number of hours before appointment where deposit is forfeited if rescheduled/cancelled.",
            ),
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("requires_deposit", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookingApp.business",
                    ),
                ),
            ],
            options={
                "unique_together": {("business", "email")},
            },
        ),
    ]
