# Generated by Django 6.0 on 2026-01-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0008_remove_business_deposit_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="accepts_deposits",
        ),
        migrations.RemoveField(
            model_name="business",
            name="deposit_type",
        ),
        migrations.RemoveField(
            model_name="business",
            name="deposit_value",
        ),
        migrations.RemoveField(
            model_name="business",
            name="reschedule_limit_hours",
        ),
        migrations.AddField(
            model_name="business",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The deposit amount required for bookings (e.g., 50.00). Set to 0 for no deposit.",
                max_digits=10,
            ),
        ),
        migrations.DeleteModel(
            name="ClientProfile",
        ),
    ]
