# Generated by Django 6.0 on 2026-01-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0009_remove_business_accepts_deposits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="amount_to_pay",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="business",
            name="deposit_percentage",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Percentage of service price (e.g. 50). Used if Deposit Type is 'Percentage'.",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="deposit_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Amount (R)"),
                    ("percentage", "Percentage (%)"),
                ],
                default="fixed",
                help_text="Choose how the deposit is calculated.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="reschedule_window_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Hours before appointment when deposit becomes non-refundable.",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fixed amount (e.g. 50.00). Used if Deposit Type is 'Fixed'.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="deposit_policy",
            field=models.TextField(
                blank=True, help_text="Rules for deposits", null=True
            ),
        ),
    ]
