# Generated by Django 6.0 on 2026-01-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0011_clientprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="deposit_exempt",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this client can book without paying a deposit.",
            ),
        ),
    ]
