# Generated by Django 6.0 on 2026-01-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0012_clientprofile_deposit_exempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_late_rescheduled",
            field=models.BooleanField(
                default=False,
                help_text="True if this appt was created from a late reschedule.",
            ),
        ),
    ]
