# Generated by Django 6.0 on 2026-01-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0013_appointment_is_late_rescheduled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="is_late_rescheduled",
        ),
    ]
