# Generated by Django 6.0 on 2026-01-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0014_remove_appointment_is_late_rescheduled"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="referral_bonus_paid",
            field=models.BooleanField(default=False),
        ),
    ]
