# Generated by Django 6.0 on 2026-01-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0015_business_referral_bonus_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingform",
            name="business",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_form",
                to="bookingApp.business",
            ),
        ),
    ]
