# Generated by Django 6.0 on 2026-01-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0016_alter_bookingform_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="buffer_time",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minutes of buffer time between appointments (e.g., 15).",
            ),
        ),
    ]
