# Generated by Django 6.0 on 2026-01-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0017_business_buffer_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="payfast_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
