# Generated by Django 6.0 on 2026-01-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0018_business_payfast_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="token_status",
            field=models.CharField(default="inactive", max_length=20),
        ),
    ]
