# Generated by Django 6.0 on 2026-01-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0019_business_token_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="deposit_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Master switch to turn deposits on/off without deleting credentials.",
            ),
        ),
    ]
