# Generated by Django 6.0 on 2026-01-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0020_business_deposit_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="If false, staff member cannot be booked."
            ),
        ),
    ]
