# Generated by Django 6.0 on 2026-01-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0021_staff_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="payfast_passphrase",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
