# Generated by Django 6.0 on 2026-01-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0023_alter_business_payfast_passphrase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="payfast_passphrase",
        ),
    ]
