# Generated by Django 6.0 on 2026-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0024_remove_business_payfast_passphrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="payfast_passphrase",
            field=models.CharField(
                blank=True,
                default="VanWyknBake420",
                help_text="Salt/Passphrase from PayFast settings.",
                max_length=255,
                null=True,
            ),
        ),
    ]
