# Generated by Django 6.0 on 2026-01-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0026_remove_business_payfast_passphrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="payfast_passphrase",
            field=models.CharField(
                blank=True,
                help_text="Match this to your PayFast 'Passphrase' setting. Leave blank if not set.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="payfast_merchant_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="payfast_merchant_key",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
