# Generated by Django 6.0 on 2026-01-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0027_business_payfast_passphrase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="custom_cancellation_message",
            field=models.TextField(
                blank=True,
                help_text="Replaces the standard text in the Cancellation email.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="custom_confirmation_message",
            field=models.TextField(
                blank=True,
                help_text="Replaces the standard text in the Booking Confirmation email.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="custom_deposit_message",
            field=models.TextField(
                blank=True,
                help_text="Replaces the standard text in the Deposit Request email.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="custom_thank_you_message",
            field=models.TextField(
                blank=True,
                help_text="Replaces the standard text in the Thank You / Review Request email.",
                null=True,
            ),
        ),
    ]
