# Generated by Django 6.0 on 2026-01-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0028_business_custom_cancellation_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="website_url",
            field=models.URLField(
                blank=True,
                help_text="Your main business website",
                max_length=500,
                null=True,
            ),
        ),
    ]
