# Generated by Django 6.0 on 2026-01-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0029_business_website_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="industry",
        ),
    ]
