# Generated by Django 6.0 on 2026-01-27 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0031_visitorlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="last_active",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_active",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
