# Generated by Django 6.0 on 2026-01-31 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0032_business_last_active_profile_last_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Number of sessions included"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for the bundle",
                        max_digits=10,
                    ),
                ),
                (
                    "valid_for_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Days until the bundle expires after purchase",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="bookingApp.business",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_in_bundles",
                        to="bookingApp.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sessions_remaining", models.PositiveIntegerField()),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchased_bundles",
                        to="bookingApp.clientprofile",
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookingApp.servicebundle",
                    ),
                ),
            ],
        ),
    ]
