# Generated by Django 6.0 on 2026-01-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0033_servicebundle_purchasedbundle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebundle",
            name="business",
        ),
        migrations.RemoveField(
            model_name="servicebundle",
            name="service",
        ),
        migrations.DeleteModel(
            name="PurchasedBundle",
        ),
        migrations.DeleteModel(
            name="ServiceBundle",
        ),
    ]
