# Generated by Django 6.0 on 2026-01-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0034_remove_servicebundle_business_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(default="Staff", max_length=50),
        ),
    ]
