# Generated by Django 6.0 on 2026-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0035_alter_staff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("founder", "Founder Plan (R199)"),
                    ("regular", "Regular Plan (R349)"),
                ],
                default="regular",
                help_text="Determines the subscription pricing.",
                max_length=20,
            ),
        ),
    ]
