# Generated by Django 6.0 on 2026-02-04 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0036_business_plan_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="bundle_count",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of sessions in bundle"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[("single", "Single Session"), ("bundle", "Bundle Package")],
                default="single",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="validity_days",
            field=models.PositiveIntegerField(
                default=90, help_text="Days until bundle expires"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("founder", "Founder Plan (R100)"),
                    ("regular", "Regular Plan (R349)"),
                ],
                default="regular",
                help_text="Determines the subscription pricing.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CustomerBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sessions_remaining", models.PositiveIntegerField()),
                ("expiry_date", models.DateField()),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_bundles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        limit_choices_to={"service_type": "bundle"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookingApp.service",
                    ),
                ),
            ],
        ),
    ]
