# Generated by Django 6.0 on 2026-02-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0038_rename_purchased_at_customerbundle_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="service",
            name="bundle_count",
        ),
        migrations.RemoveField(
            model_name="service",
            name="service_type",
        ),
        migrations.RemoveField(
            model_name="service",
            name="validity_days",
        ),
        migrations.AddField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="bookingApp.clientprofile",
            ),
        ),
        migrations.DeleteModel(
            name="CustomerBundle",
        ),
    ]
