# Generated by Django 6.0 on 2026-02-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0039_remove_appointment_customer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="client",
            new_name="customer",
        ),
    ]
