# Generated by Django 6.0 on 2026-02-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0040_rename_client_appointment_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="BundleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookingApp.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valid_for_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Days until the bundle expires after purchase",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="bookingApp.business",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        through="bookingApp.BundleItem", to="bookingApp.service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("remaining_sessions", models.JSONField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_bundles",
                        to="bookingApp.clientprofile",
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookingApp.servicebundle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bundleitem",
            name="bundle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bookingApp.servicebundle",
            ),
        ),
    ]
