# Generated by Django 6.0 on 2026-02-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookingApp", "0041_bundleitem_servicebundle_purchasedbundle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebundle",
            name="services",
        ),
        migrations.RemoveField(
            model_name="purchasedbundle",
            name="bundle",
        ),
        migrations.RemoveField(
            model_name="purchasedbundle",
            name="client",
        ),
        migrations.RemoveField(
            model_name="servicebundle",
            name="business",
        ),
        migrations.DeleteModel(
            name="BundleItem",
        ),
        migrations.DeleteModel(
            name="PurchasedBundle",
        ),
        migrations.DeleteModel(
            name="ServiceBundle",
        ),
    ]
